#!/bin/bash

# https://superuser.com/questions/544989/does-tmux-sort-the-path-variable
#if [ -f /etc/profile ]; then
#    PATH=""
#    source /etc/profile
#fi

PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
PATH="$(brew --prefix ed)/libexec/gnubin:$PATH"
PATH="$(brew --prefix findutils)/libexec/gnubin:$PATH"
PATH="$(brew --prefix gnu-indent)/libexec/gnubin:$PATH"
PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH"
PATH="$(brew --prefix gnu-tar)/libexec/gnubin:$PATH"
PATH="$(brew --prefix gnu-which)/libexec/gnubin:$PATH"
PATH="$(brew --prefix grep)/libexec/gnubin:$PATH"

set -o vi
