set -g status-position top
set -g status-bg "#1d2021"
set -g status-fg white
set -g status-left '@#h '
set -g status-right ''
set -w -g window-status-current-style "fg=white,bold"
#set -g pane-border-style 'bg=colour233 fg=colour148'


## Show bells in window titles.
set -g window-status-bell-style fg=yellow,bold,underscore


